INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Amol', 'Solanke');
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Dipika', 'Pawar');
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Mitali', 'Kolhe');
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Mahesh', 'Shinde');
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Chetan', 'Roman');
